[build]
  command = "npm run build"
  functions = ".next/api" # Specify the path to your serverless functions directory

[[redirects]]
  from = "/api/*" # Redirect requests made to /api/* to your serverless functions
  to = ".next/api/:splat"
  status = 200
